### ISSUE TITLE
Upload to Nuget

### ISSUE THREAD

**Issue by Mart-Bogdan** [biboudis/LambdaMicrobenchmarking#1]
Please upload this package to NuGet

**Comment by Mart-Bogdan** [comment]
I've published it here https://www.nuget.org/packages/LambdaMicrobenchmarking/
Please register on NuGet, and I'll add you as Package owner.

**Comment by biboudis** [comment]
Hi @Mart-Bogdan! Thanks!

I have created an account user name: biboudis.

**Comment by Mart-Bogdan** [comment]
Ok, you should receive e-mail with invitation.
New versions can be uploaded via command line/ (via gui)[http://docs.nuget.org/docs/creating-packages/using-a-gui-to-build-packages]/ or on web site, buy uploading built package, pckaged from command line or gui

**Comment by biboudis** [comment]
Great! Will do! We can enable automatic uploading via appveyor at some point I guess.

I will update README. Thanks!
